#!/usr/bin/env python3
name: quote_tool
channels:
  - conda-forge
  - defaults
dependencies:
  # Try to install everything via conda where possible,
  #   makes for simpler and quicker installs
  - python=3.8.13
  - numpy
  - pandas
  - openpyxl
  - matplotlib
  - nltk=3.7
  - spacy=3.3.1
  - spacy-model-en_core_web_lg
  - ipywidgets=7.6.5
  - blis=0.7.8
  - boto3=1.24.18
  - botocore=1.27.18
  - certifi=2022.6.15
  - chardet=5.0.0
  - Click=8.1.3
  - cymem=2.0.6
  - docutils=0.18.1
  - Flask=2.1.2
  - gunicorn=20.1.0
  - idna=3.3
  - itsdangerous=2.1.2
  - Jinja2=3.1.2
  - jmespath=1.0.1
  - jsonschema=4.6.0
  - MarkupSafe=2.1.1
  - murmurhash=1.0.7
  - neuralcoref=4.0
  - plac=1.3.5
  - preshed=3.0.6
  - pymongo=4.1.1
  - python-dateutil=2.8.2
  - pytz=2022.1
  - requests=2.28.0
  - s3transfer=0.6.0
  - six=1.16.0
  - srsly=2.4.3
  - thinc=8.0.17
  - tqdm=4.64.0
  - urllib3=1.26.9
  - wasabi=0.9.1
  - Werkzeug=2.1.2
  - xlrd=2.0.1
  #- pip
  #- pip:
      